language: node_js
node_js: stable
# dist: trusty
# addons:
#   apt:
#     packages:
#       # This is required to run new chrome on old trusty
#       - libnss3
# notifications:
#   email: false

# allow headful tests
# before_install:
#   # Enable user namespace cloning
#   - "sysctl kernel.unprivileged_userns_clone=1"
#   # Launch XVFB
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install

script:
  - npm run build
  - npm run upload "${AppId}" "${Region}" "${SecretId}" "${SecretKey}" "${Bucket}"

after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./dist/
  - cd ./dist
  - git init 
  - git config user.name "BiYuqi"
  - git config user.email "biyuqiwan@163.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${VueNotes}@${GH_REF}" master:gh-pages

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/BiYuqi/fe-navigation.git