export const headMapping = {
  'personal-blog': '个人博客',
  'awesome-team': '优秀团队',
  'tech-community': '技术社区',
  'learning-anything': '交互式脑图',
  'javascript': 'Javascript',
  'jquery': 'JQuery',
  'VueJs': 'VueJs',
  'vue-around': 'Vue周边',
  'React': 'ReactJs',
  'react-native': 'React Native',
  'wechat-doc': '小程序文档',
  'wechat-community': '小程序社区',
  'wechat-toturial': '小程序教程',
  'angular-doc': 'Angular文档',
  'angular-toturial': 'Angular教程',
  'nodejs': 'NodeJs',
  'mobile-develop': '移动端开发',
  'mobile-ui': '移动UI',
  'mobile-toturial': '移动端教程',
  'Webpack': 'Webpack',
  'Css': 'CSS',
  'develop-tool': '开发工具',
  'develop-rule': '代码规范',
  'open-source': '开源库',
  'frontend-toturial': '前端教程总结',
  'regexp-topic': '正则专题',
  'd3': 'D3.Js',
  'opening-source-tool': '开源工具',
  'npm-library': 'npm常用组件库',
  'framework-topic': '框架专题',
  'Git': 'Git',
  'interview': '面试宝典',
  'python': 'Python',
  'deep-learning': '深度学习',
  'PHP': 'PHP',
  'python-blog': 'Python博客',
  'online-h5': '在线H5制作平台',
  'code-named': ' 变量命名',
  'only-tool': '实用工具',
  'online-coding': '在线编程',
  'build-tool': '构建工具'
}
